### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MarkSwanson** [mystor/rust-cpp#1]
Just a friendly nudge to get it compiling again against nightly.
I'm curious to play with this.

**Comment by mystor** [comment]
Yeah, sorry I don't have it compiling right now - I have a nightly build which runs on travis, so if you want to find a version of nightly you can play with, just look on travis and see the last time it was building :)

I just don't have the time to fix it within the day most of the time - I'm fairly busy with everything else I'm working on at the same time. If you are interested in fixing the compile errors (usually they're because the rust developers moved something around internally) I'd be super excited about a PR :D.

**Comment by mystor** [comment]
I never closed this when I fixed the problem - oops
